server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
spring:
  application:
    name: product-system-api
  datasource:
    url: ${JDBC_URL}
    username: postgres
    password: Ygbm!MEPn3rZp%4!09F*
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: WARN