server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: users-system-api
  mvc:
    log-request-details: true
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
management:
  observations:
    annotations:
      enabled: true
