server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: users-system-api
  mvc:
    log-request-details: true
  datasource:
    driver-class-name: org.postgresql.Driver
    # url: jdbc:postgresql://terraform-20250226131959431600000001.cvm02qq6cdnp.sa-east-1.rds.amazonaws.com/order_gen
    url: ${JDBC_URL}
    username: postgres
    password: Ygbm!MEPn3rZp%4!09F*
  jpa:
    hibernate:
      ddl-auto: update
management:
  observations:
    annotations:
      enabled: true
logging:
  level:
    root: WARN
